# Generated by Django 5.0 on 2026-04-25 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
